apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - serviceaccount.yaml
  - rolebinding.yaml
  - networkpolicy-default-deny.yaml
  - limitrange.yaml
  - resourcequota.yaml
